name: pack & deploy to NuGet.org

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # Ändere dies entsprechend deiner .NET-Version

    - name: Define Package Version
      id: package_version
      run: echo "PACKAGE_VERSION=$(git tag --sort=v:refname | tail -n 1 | sed 's/v//')" >> $GITHUB_ENV

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Pack
      run: dotnet pack --configuration Release --no-build --output nupkgs

    - name: Publish NuGet Package
      run: dotnet nuget push ./nupkgs/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
